### ISSUE TITLE
somtimes it doesn't work well

### ISSUE THREAD

**Issue by gongwk** [Canjie-Luo/MORAN_v2#10]
I have run the demo which you provide，but in some cases， it seems that not work well.  Maybe i don't completely understand how it works.
![pof09_7q gl 9ro83 24v17](https://user-images.githubusercontent.com/14072360/51359803-3a184900-1b04-11e9-825f-0e788ce32d42.png)
![2h8ppp65mo4da1q7amxtt](https://user-images.githubusercontent.com/14072360/51359839-63d17000-1b04-11e9-9b95-711dcd94439c.png)
![kqxw4 7u zpbu2focch znn](https://user-images.githubusercontent.com/14072360/51359899-90858780-1b04-11e9-8f2f-74ede3996959.png)
![up8d sl6qn1p ytx wpdl](https://user-images.githubusercontent.com/14072360/51359905-94b1a500-1b04-11e9-9336-4d101bd53573.png)
Above the example，Does it means that this algorithm is not suitable for words with large curvature？Forgive my poor english.

**Comment by Canjie-Luo** [comment]
By coincidence. you chose the false example which was reported in our paper.:sweat_smile: MORAN works well on small angle curve text. For larger angle curve text, it may need a favor of a text detector, which was also stated in our paper.

**Comment by gongwk** [comment]
Got it, thanks for your answer.

**Comment by Canjie-Luo** [comment]
For academic research, the MORAN is trained by using only synthetic samples. If you use more real data to train the model, the MORAN will gain better performance. @gongwk

**Comment by Canjie-Luo** [comment]
![1](https://user-images.githubusercontent.com/32130508/51362730-be23fe00-1b0f-11e9-9a20-ee9b9d3cbfd3.jpg)
![2](https://user-images.githubusercontent.com/32130508/51362731-be23fe00-1b0f-11e9-9372-8cc3da6d805b.jpg)
![3](https://user-images.githubusercontent.com/32130508/51362729-bd8b6780-1b0f-11e9-9033-4e67ea1f119f.jpg)
