### ISSUE TITLE
The performance is low

### ISSUE THREAD

**Issue by hoangtubatu123** [Canjie-Luo/MORAN_v2#101]
i tried to train with my custom data. It perform well in my train/test, but when i use the model to test external data, it is not good. Can you help me ???

**Comment by jun214384468** [comment]
Hello, I want to know what these three indicators mean  --train_nips, --train_cvpr, --valroot.

**Comment by Canjie-Luo** [comment]
Please refer to https://github.com/Canjie-Luo/MORAN_v2#data-preparation. @jun214384468

**Comment by jun214384468** [comment]
> Please refer to https://github.com/Canjie-Luo/MORAN_v2#data-preparation. @jun214384468
好的 ，谢谢
