### ISSUE TITLE
Is there any rectified methods processing arbitrary length samples without fixed input(e.g. 32x100) in a batch

### ISSUE THREAD

**Issue by liangzimei** [Canjie-Luo/MORAN_v2#102]
Thanks for your great work , it does work. 
However, in practice,  to handle very long text (train set has no such long samples) in inference phase, we often train a model keeping the ratio and padding rather than fixed input(e.g. 32*100).  
When there is no rectified module, it works successfully. when adding a rectified module, keeping ratio and padding is difficult. 
Is there any rectified methods processing arbitrary length samples without fixed input(e.g. 32x100) in a batch?
Thanks in advance……

**Comment by Canjie-Luo** [comment]
Thanks for your support! 

Actually, I proposed MORAN to address small range deformation of text. As your irregular text is very long, I am afraid that the text in a semicircle is too difficult to rectify. You may need a curve text detector.

The output size of the rectification network of MORAN is not fixed (different from ASTER, which fix the number of the points). Theoretically, the rectification network of MORAN is able to be trained with fix input, and generalize well on the text with variable length. 

For long text, a CRNN-based recognizer trained using CTC loss usually performs better. (It is reported by several papers that attention mechanism performs well only on short text.)

**Comment by liangzimei** [comment]
Thanks for your reply. i will then try a curve text detector and use its outline to rectify.

**Comment by liangzimei** [comment]
@Canjie-Luo  hello, sorry to bother you,  can you give some links about the papers saying  that attention mechanism performs well only on short text? thanks……

**Comment by Canjie-Luo** [comment]
[[ICDAR 2019] A Comparative Study of Attention-based Encoder-Decoder Approaches to Natural Scene Text Recognition.pdf](https://github.com/Canjie-Luo/MORAN_v2/files/3804709/ICDAR.2019.A.Comparative.Study.of.Attention-based.Encoder-Decoder.Approaches.to.Natural.Scene.Text.Recognition.pdf)

**Comment by Canjie-Luo** [comment]
Can you give the rectified image?
