### ISSUE TITLE
resume training

### ISSUE THREAD

**Issue by johnSmith1990** [Canjie-Luo/MORAN_v2#103]
Hi,  I download pretrain model and created lmdb of my train and validation dataset. I divide my dataset for training(50%), testing(30%) and validation(20%). 
my question is that how to modify train command : 
       ```
 --train_nips path_to_dataset \
	--train_cvpr path_to_dataset \
	--valroot path_to_dataset \```

while `train_nips` and `train_cvpr` are required but i have one dataset. thanks.

**Comment by jun214384468** [comment]
我也想问同样的问题，希望帮忙解答一下。

**Comment by Canjie-Luo** [comment]
An easy way is to set the `train_nips` and `train_cvpr` the same. Or modify the 
https://github.com/Canjie-Luo/MORAN_v2/blob/2cd40c41d6041f54efdbdcb7d7e081231168c468/main.py#L75
to 
`train_dataset = dataset.lmdbDataset(root=opt.train_root, 
transform=dataset.resizeNormalize((opt.imgW, opt.imgH)), reverse=opt.BidirDecoder)`
You should modify all related code in `main.py`.

**Comment by jun214384468** [comment]
是的，我将那两个设置成一样的路径了。

**Comment by johnSmith1990** [comment]
thanks. my goal is to resume training with my own dataset. My dataset has only one special character +` 0-9` and` a-z` (38 char's). My `training `images are `316,000` and `validation `images are `144,000 `images. during `training`, this line of `main.py` `print("correct / total: %d / %d, "  % (n_correct, n_total))` prints `n_total `:`64,000`. why 64000? None of my `training `and `testing `images are `64,000`. other note is that `acc `during training reach `99%` but when i load trained model and test some images with `demo.py`, `acc `is `0` and all of predictions are `wrong`. I `resume  `training with your `demo.pth` but actually, results of `demo.pth` is very very better than new trained models. 

Can you help me what was wrong? thanks

**Comment by sssimpleboy** [comment]
> 是的，我将那两个设置成一样的路径了。

大佬，他有三个路径，我只有一个数据集，我把前两个设置成一样，那么第三个该怎么办呢？谢谢
