### ISSUE TITLE
有没有方法在不用pytorch0.3.1的情况下运行版本，比如0.4.1

### ISSUE THREAD

**Issue by xo123** [Canjie-Luo/MORAN_v2#106]
如果你有空看到了请回复下

**Comment by Canjie-Luo** [comment]
只需要将相关操作改为0.4.1的特性即可，例如variable()改为tensor()。效果理论上是没有差别的。

**Comment by xo123** [comment]
十分感谢您的回复，我已经能够运行了。谢谢!------------------ 原始邮件 ------------------
发件人: "Canjie Luo"<notifications@github.com>
发送时间: 2019年11月20日(星期三) 上午10:42
收件人: "Canjie-Luo/MORAN_v2"<MORAN_v2@noreply.github.com>;
抄送: "xo123"<1484497818@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Canjie-Luo/MORAN_v2] 有没有方法在不用pytorch0.3.1的情况下运行版本，比如0.4.1 (#106)



只需要将相关操作改为0.4.1的特性即可，例如variable()改为tensor()。效果理论上是没有差别的。
 
&mdash;

**Comment by Canjie-Luo** [comment]
谢谢关注。
