### ISSUE TITLE
中文辨識以及文本檢測需求！

### ISSUE THREAD

**Issue by kaonick** [Canjie-Luo/MORAN_v2#108]
您好，早上 從paperswithcode找到這裏。
實測的結果，效果超猛，真是太神啦。(我目前為止試過英數字辨識最魯棒的...扭曲、缺角都認得出來)

不過除了測試英數字的效果，請問有測試訓練過中文嗎？或是有這樣的計劃嗎？

另外我目前的理解是針對文本偵測框選擷取後，再用MORAN進行文字辨識，只是若想要辨識一份文件時，還需要先偵測到其中的文本，這一段是不是需要另外使用像TextBox...之類的，還是我的理解有誤？

不好意思，隨便亂問，不過真的是謝謝。

**Comment by Canjie-Luo** [comment]
你好，谢谢关注。MORAN可以稍微纠正不规则样本，不过没有那么厉害啦。
多个文本行的话，需要先做检测，切割出相应的文本区域，再做识别。中文任务的话，建议使用CRNN，可以在CRNN网络前边接上我们的纠正器，理论上也可以联合训练的。

**Comment by kaonick** [comment]
哈哈！真的很不錯哦！
我們要辨識從棧板上的包裝噴印文字，因為包裝像水泥袋，印在上面的字會扭曲，而且噴印的字，有缺角，之前辨識一真不穩定，那天試你的模型，很準哦！

**Comment by Canjie-Luo** [comment]
谢谢！如果您方便的话，能麻烦您分享一两张demo看看吗？

**Comment by kaonick** [comment]
[https://drive.google.com/file/d/1UpNivHdzUbFJwzPmqNTjGkOnBuDVLCup/view](url)

**Comment by Canjie-Luo** [comment]
看到了哈，好像也没有多难啊哈哈。我的另一个repo可以做增广，训练其他识别器，应该也是能识别的～

**Comment by kaonick** [comment]
擴增REPO我之前也有看到，
有機會再試看看。

可能我們太肉腳了(台灣用語，牛逼的相反)，我一開始用Tesseract，然後用dhash,ahash,phash，還用googlenet(v1~v3)等一些模型，都效果一般般，所以才驚為天人....

**Comment by Canjie-Luo** [comment]
CRNN，ASTER，也都是不错的
