### ISSUE TITLE
BidirDecoder=False Error！

### ISSUE THREAD

**Issue by kaonick** [Canjie-Luo/MORAN_v2#109]
當我測試單向(左至右)辨識，出現異常？
出現在demo.py中的
MORAN.load_state_dict(MORAN_state_dict_rename)
這一行。

訊息顯示是模型與pth不匹配。

後來我看asrn_res.py，問題好像是出在BidirDecoder在True與False使用的attention名稱不一致。
在True時是使用attentionL2R及attentionR2L
而False時是使用attention
pth中只有attentionL2R及attentionR2L

後來我試著將False也改成attentionL2R及attentionR2L好像就可以了！
(當然demo.py的內容也要修改)

不知道是不是bug，提報出來。

**Comment by Canjie-Luo** [comment]
是的，我们给出的模型参数是双向的。
