### ISSUE TITLE
Suggestion: Add some automated testing like Travis CI, Circle CI, Appveyor

### ISSUE THREAD

**Issue by cclauss** [Canjie-Luo/MORAN_v2#11]
They are all _free_ for Open Source projects like this one.

https://github.com/marketplace/category/continuous-integration

If you pick one then I will create a config file to get the automated testing started,

**Comment by Canjie-Luo** [comment]
I used Travis CI before. But just try the one you like. Thanks again!

**Comment by cclauss** [comment]
Closed in #12
