### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'BidirDecoder'

### ISSUE THREAD

**Issue by zobeirraisi** [Canjie-Luo/MORAN_v2#112]
I get the above error when I want to run the `demo.py` code for multiple images?

**Comment by Canjie-Luo** [comment]
You can modify the `demo.py` to meet your requirement~

**Comment by alexramirez13** [comment]
Hi,
I get the same error when I run demo.py  in a folder with multiple images. I made the appropriate changes and the first image in the folder works well but with the second I get the error above.

**Comment by dPacc** [comment]
If you are running this on a Jupyter Notebook, this is how I fixed the "TypeError: forward() got an unexpected keyword argument 'BidirDecoder' #134"

Just import the libraries again before running this part of the code

```
cuda_flag = False
if torch.cuda.is_available():
    cuda_flag = True
    MORAN = MORAN(1, len(alphabet.split(':')), 256, 32, 100, BidirDecoder=True, CUDA=cuda_flag)
    MORAN = MORAN.cuda()
else:
    MORAN = MORAN(1, len(alphabet.split(':')), 256, 32, 100, BidirDecoder=True, inputDataType='torch.FloatTensor', CUDA=cuda_flag)
```
