### ISSUE TITLE
您好！请教您一些问题

### ISSUE THREAD

**Issue by tzhxs** [Canjie-Luo/MORAN_v2#115]
我在ocr方面还算是新手，运行了您的代码之后有一些疑问。我发现模型似乎没有办法识别空格(被认为是背景？)，如果想要自动识别并分开两个单词应该怎么做呢？使用包含空格的数据集训练吗？

**Comment by Canjie-Luo** [comment]
是的，您说的对，原来的训练集中没有空格。建议使用和任务相对应的数据集。

**Comment by tzhxs** [comment]
好的，非常感谢！请问后续是否会release包含中文和空格的预训练模型？

**Comment by Canjie-Luo** [comment]
如果有学术上的创新我们会继续维护～如果是工程上的支持，我们应该不会更新。

**Comment by tzhxs** [comment]
好的，非常感谢！
