### ISSUE TITLE
can we do without the lmdb data format ?? directly loading images and labels from disk?

### ISSUE THREAD

**Issue by gstechgeek** [Canjie-Luo/MORAN_v2#116]
I forked your repository and made a few changes in the lmdbDataset class to accomodate training from images directly loaded from the disk instead of using an intermediate file format like lmdb.
I'm trying to train on the IIIT5k dataset. The Class is as follows:
```
class lmdbDataset(Dataset):
    """
        New Dataloader Class
    """ 
    def __init__(self, rootfile, transform=None, reverse=False, mode=True, alphabet='0123456789abcdefghijklmnopqrstuvwxyz'):
        self.rootfile = rootfile
        self.transform = transform
        self.alphabet = alphabet
        self.reverse = reverse
        self.listIdx = []
        self.img_loc = []
        self.text = []
        split = 0.75

        with open(rootfile, 'r') as f:
            self.listIdx = f.readlines()

        if mode:
            self.listIdx = self.listIdx[:int(split * len(self.listIdx))]
        else:
            self.listIdx = self.listIdx = self.listIdx[int(split * len(self.listIdx)):]

        for i in range(len(self.listIdx)):
            loc, txt = self.listIdx[i].split('\n')[0].split(':')
            self.img_loc.append(loc)
            self.text.append(txt)

    def __len__(self):
        return len(self.listIdx)

    def __getitem__(self, idx):
        img = Image.open(self.img_loc[idx]).convert('L')
        label = self.text[idx]
        label = ''.join(label[i] if label[i].lower() in self.alphabet else ''
                for i in range(len(label)))
        if len(label) <= 0:
            return self[idx + 1]
        if self.reverse:
            label_rev = label[-1::-1]
            label_rev += '$'
        label += '$'

        if self.transform is not None:
            img = self.transform(img)

        if self.reverse:
            return (img, label, label_rev)
        else:
            return (img, label)
```
The image file locations and respective labels are given as follows:
(P.S image locations and filenames can be stored in seperate files. This is what I used at the moment.)
```
dataset/IIIT5K/train/1009_2.png:YOU
dataset/IIIT5K/train/1017_1.png:RESCUE
dataset/IIIT5K/train/1017_2.png:MISSION
dataset/IIIT5K/train/1021_1.png:HOME
dataset/IIIT5K/train/1023_1.png:BORDER
dataset/IIIT5K/train/1023_10.png:DODA
dataset/IIIT5K/train/1023_11.png:BATOTE
dataset/IIIT5K/train/1023_15.png:143KM
dataset/IIIT5K/train/1023_16.png:193KM
dataset/IIIT5K/train/1023_17.png:315KM
dataset/IIIT5K/train/1023_18.png:PLEASE
dataset/IIIT5K/train/1023_2.png:ROADS
dataset/IIIT5K/train/1023_3.png:ORGANISATION
dataset/IIIT5K/train/1023_4.png:WISHES
dataset/IIIT5K/train/1023_8.png:CHINGAM
dataset/IIIT5K/train/1023_9.png:KISHTWAR
dataset/IIIT5K/train/1026_10.png:KUMAR
dataset/IIIT5K/train/1026_2.png:CARD
dataset/IIIT5K/train/1026_4.png:4377
dataset/IIIT5K/train/1026_6.png:0123
dataset/IIIT5K/train/1035_1.png:OF
dataset/IIIT5K/train/1035_2.png:INDIA
dataset/IIIT5K/train/1035_3.png:STATE
dataset/IIIT5K/train/1036_4.png:INDIA
dataset/IIIT5K/train/1044_1.png:SAVE
dataset/IIIT5K/train/1044_2.png:THE
dataset/IIIT5K/train/1044_3.png:LOSE
dataset/IIIT5K/train/1045_3.png:OF
dataset/IIIT5K/train/1045_4.png:INDIA
dataset/IIIT5K/train/1045_5.png:SAJITH
dataset/IIIT5K/train/1045_6.png:ERATTUPETTA
dataset/IIIT5K/train/1046_4.png:A
dataset/IIIT5K/train/1046_5.png:PARTNER
dataset/IIIT5K/train/1046_6.png:FOR
```

**Comment by gstechgeek** [comment]
I forked your repository and made a few changes in the lmdbDataset class to accomodate training from images directly loaded from the disk instead of using an intermediate file format like lmdb. 
I'm trying to train on the IIIT5k dataset with the following parameters:

_BidirDecoder=True, 
MORAN='', 
adadelta=True, 
adam=False, 
alphabet='0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:g:h:i:j:k:l:m:n:o:p:q:r:s:t:u:v:w:x:y:z:$', 
batchSize=20, 
beta1=0.5, 
cuda=True, 
displayInterval=100, 
experiment='output/myexp', 
imgH=64, imgW=200, 
lr=0.25, 
n_test_disp=10, 
ngpu=1, 
nh=256, 
niter=1000, 
saveInterval=40000, 
sep=':', 
sgd=False, 
targetH=32, targetW=100, 
# train_cvpr='myLMDB/', 
# train_nips='myLMDB/', 
# valroot='myLMDB/', 
valInterval=1000,
workers=4_

and getting only 15% accuracy at best.

**Comment by Canjie-Luo** [comment]
Of course you can. But please make sure that the speed of data loading meets the requirement of training.

**Comment by premtibadiya** [comment]
TypeError: __init__() got an unexpected keyword argument 'root'
 
Getting this error when updating the lmbdDataset class from the dataset.py file to the above code. And then runnig the main file

**Comment by premtibadiya** [comment]
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

I am getting this error when putting the labels.txt file in the --train_data argument
