### ISSUE TITLE
一则关于训练的问题

### ISSUE THREAD

**Issue by goodboyliang** [Canjie-Luo/MORAN_v2#117]
您好！我按照README中的要求进行配置，对于包含2077张图片的测试集，每张图片的识别结果竟然都是差不多的（导致准确率为零），请问是哪里出了问题呢？谢谢！

**Comment by Canjie-Luo** [comment]
您好，谢谢关注。建议先用预训练模型来预测，看看基本流程是不是没问题的，再进行您的实验。
