### ISSUE TITLE
Can you provide evaluation scripts?

### ISSUE THREAD

**Issue by dpengwen** [Canjie-Luo/MORAN_v2#118]
Hi,
  Thanks for sharing the code! Could you share the evaluation script? I cannot evaluate the accuracy based on the demo.py. This is because demo.py would generate two results (left-to-right prediction and right-to-left prediction). There are no corresponding predicted scores, so I do not know to choose which one.  How can I obtain the corresponding predicted scores? 

Looking forward to your replay.

Thank you ~

**Comment by Canjie-Luo** [comment]
Please follow the following code.
https://github.com/Canjie-Luo/MORAN_v2/blob/2cd40c41d6041f54efdbdcb7d7e081231168c468/main.py#L170-L176
