### ISSUE TITLE
Vertical Text

### ISSUE THREAD

**Issue by farleyschaefer** [Canjie-Luo/MORAN_v2#119]
As stated in the end of the paper: 

> However, the MORAN is not designed for vertical text. Our method was proposed for the complicated deformation of text within a cropped horizontal rectangle.

Would you be able to elaborate on why this is, and if it would be trivial to adjust the network to support vertical text.

Cheers.

**Comment by Canjie-Luo** [comment]
Thanks for your attention. One potential solution is to rotate the images (90 degree or -90 degree) of both the training and testing sets. Our new work [DAN (2D attention)](https://github.com/Wang-Tianwei/Decoupled-attention-network) is also worth a try.

**Comment by farleyschaefer** [comment]
Cheers, will give that a try. Closing for now.
