### ISSUE TITLE
AssertionError: the height of conv must be 1

### ISSUE THREAD

**Issue by bartengine27** [Canjie-Luo/MORAN_v2#121]
Dear,

  Thanks for making your source available!

  After building an lmdb dataset and starting train_MORAN.sh, I encounter the following error:
`
AssertionError: the height of conv must be 1
`
Any idea how I can debug that?

Thanks,
Bart

**Comment by bartengine27** [comment]
The issue above is related to the image size, if I use a size different from the size in main.py, I get the error above.

What should be changed to accept larger images?

thanks,
Bart

**Comment by Canjie-Luo** [comment]
Thanks for your attention. The default height for ASRN is set to 32. If you use a size different from mine, please customize the encoder in the ASRN to make sure the height of `conv` is 1 or use a 2D decoder in the ASRN.
