### ISSUE TITLE
论文中的一个小细节问题

### ISSUE THREAD

**Issue by fuyongXu** [Canjie-Luo/MORAN_v2#122]
你好，请问一下在论文中有这么一句话
Before sampling, the x-coordinate and y-coordinate on the offset maps are normalized to [0; W ] and [0; H],respectively.
但是在代码中我好像没有看到这样的实现。

**Comment by Canjie-Luo** [comment]
https://github.com/Canjie-Luo/MORAN_v2/blob/2cd40c41d6041f54efdbdcb7d7e081231168c468/models/morn.py#L69

我们的v2版本直接用了PyTorch的官方函数。
