### ISSUE TITLE
Are the training images cropped?

### ISSUE THREAD

**Issue by smolendawid** [Canjie-Luo/MORAN_v2#123]
As far as I understand the training datasets are not cropped. So how is MORAN trained - as an end-to-end system, or rather the texts are somehow cropped and MORAN is more text-detector? How are images cropped?
I can't get it from the paper, thank you

**Comment by smolendawid** [comment]
@Canjie-Luo I would really appreciate your explanation. I assume training images were cropped but I'd like to confirm they were cropped using boxes metadata available in the synthetic training datasets.

**Comment by Canjie-Luo** [comment]
Yes, the MORAN is a recognizer for ***cropped text images***. The training dataset (Synthetic data for text localization in natural images, CVPR 2016) provides the annotation of text bounding boxes. The text regions are then cropped as training samples.

**Comment by smolendawid** [comment]
Thank you a lot
