### ISSUE TITLE
would you please share pure python code of grid_sample function?

### ISSUE THREAD

**Issue by asonee** [Canjie-Luo/MORAN_v2#124]
作者，您好，非常感谢你的工作！！！
请问可以给出grid_sample的纯python代码？因为我在将Pytorch的模型转换为tensorflow时，发现tensorflow没有grid_sample函数，请问一下，您有实现grid_sample的纯python代码？

**Comment by Canjie-Luo** [comment]
抱歉，我用的是PyTorch的接口。建议您把PyTorch相关函数定制化到您的应用中。

**Comment by asonee** [comment]
感谢回复！那我自己重写下这个函数.
