### ISSUE TITLE
A question about using the model without Bidirdecoder

### ISSUE THREAD

**Issue by JinGyeSetBirdsFree** [Canjie-Luo/MORAN_v2#125]
Here is the code about postprocess without Bidirdecoder:   
            cpu_images, cpu_texts = data
            utils.loadData(image, cpu_images)
            t, l = converter.encode(cpu_texts, scanned=True)
            utils.loadData(text, t)
            utils.loadData(length, l)
            preds = MORAN(image, length, text, text_rev, test=True)
            cost = criterion(preds, text)
            _, preds = preds.max(1)
            preds = preds.view(-1)
            sim_preds = converter.decode(preds.data, length.data)

I'm confused that should it be added 'sim_preds = [i.split('$')[0] + '$'  for i in sim_preds]'  in the end.

**Comment by Canjie-Luo** [comment]
您好，看到您在开发一个OCR repo，挺不错！
您的建议是对的。这里的‘$’作为终止符，可以按照您的需要来处理。更合理的做法是在Attention机制中遇到‘$’就停止解码。我的repo还是比较初级，希望抛砖引玉～

**Comment by JinGyeSetBirdsFree** [comment]
谢谢鼓励，也感谢您的代码，给了我很大启发 :)
