### ISSUE TITLE
Max length of text line that model can recognize well?

### ISSUE THREAD

**Issue by Cabbagehust2507** [Canjie-Luo/MORAN_v2#127]
I want to use your model to recognize line text. But I'm not sure about the max length that model can recognize. Can you tell me about that? Thank you so much!

**Comment by Canjie-Luo** [comment]
For long text recognition, I recommend CTC-based recognizers.

**Comment by Cabbagehust2507** [comment]
> For long text recognition, I recommend CTC-based recognizers.

Thank you so much. I will try it.
