### ISSUE TITLE
中文训练问题

### ISSUE THREAD

**Issue by lim-0** [Canjie-Luo/MORAN_v2#128]
您好，测试后发现模型效果非常好！！是目前看效果最好的模型。但是我训练了少量中文数据（包含字母和英文）发现数字和英文能识别，但中文一个也识别不出来无法识别，请问您有什么建议吗？

**Comment by lim-0** [comment]
已解决

**Comment by lim-0** [comment]
lmdbDataset内的字符对应表未修改，修改后可以识别。

**Comment by sssimpleboy** [comment]
请问您的中文数据是咋来的？谢谢
