### ISSUE TITLE
文字寬、高問題？

### ISSUE THREAD

**Issue by kaonick** [Canjie-Luo/MORAN_v2#133]
您好：
因為場景的文字的寬、高不定，
我看在forward中的resizeNormalize_opencv(100,32)，會固定將輸入圖片縮放成(100寬,32高)，
不知道這樣的理解對不對！
如果是的話，若是文字多一點的時候，每個字會被壓的很扁，會因此造成辨識效果不佳，
請問針對此問題，您是如何處理？(需要自已切割輸入圖片的寬度嗎？)

**Comment by Canjie-Luo** [comment]
你好，这里的设置是给普通英文单词的，需要根据具体的识别任务来调整设置。谢谢。
