### ISSUE TITLE
关于中文识别的有关问题

### ISSUE THREAD

**Issue by whuhangzhang** [Canjie-Luo/MORAN_v2#135]
@Canjie-Luo 你好，我查看了您的issue列表，想问 MORAN_v2和Decoupled-attention-network两个repo哪一个比较适合ICDAR2019 ReCTS这样的数据集呢？在您之前的回答中，您推荐CRNN作为长中文本的识别，但是对于ReCTS的数据集，哪一个方法效果会比较好呢？
https://github.com/Canjie-Luo/MORAN_v2/issues/32
https://github.com/Canjie-Luo/MORAN_v2/issues/119

**Comment by Canjie-Luo** [comment]
你好，建议使用Decoupled-attention-network或者CRNN-based的识别方法。

**Comment by whuhangzhang** [comment]
DAN-2D这种方法是指Decoupled-attention-network这篇文章么？
