### ISSUE TITLE
这个模型适合中文不，准确率怎么样？

### ISSUE THREAD

**Issue by Jiakui** [Canjie-Luo/MORAN_v2#2]
有人用这个模型搞过中文识别吗？ 效果好不好呢   。。。。。

**Comment by Canjie-Luo** [comment]
理论上都可以使用。不过中文一般是长文本，比较少出现弯曲短文本的情况，和单词级别的英文有所不同。

**Comment by Jiakui** [comment]
您的意思是这个方法不适合长文本识别？

**Comment by Canjie-Luo** [comment]
有更加具体的应用场景吗？或者给一两张demo图像？

**Comment by zzhanq** [comment]
你好，请问，比如类似于扫描件的中文识别这样的场景，本方法如何？

**Comment by Canjie-Luo** [comment]
不太清楚您那边遇到的问题，扫描件背景噪声一般没有这么复杂，印刷文本也一般不会有多样的形变，所以本课题有一点区别。目前已经有很多成熟的产品，也有很多公司开放了接口（免费和付费都有），都可以尝试一下。

**Comment by Crescentz** [comment]
比如说，成熟的有。。什么repo 非接口

**Comment by Crescentz** [comment]
> 你好，请问，比如类似于扫描件的中文识别这样的场景，本方法如何？

你好，请问大哥最后你是找到什么好方法了吗

**Comment by Crescentz** [comment]
@zzhanq 

> 你好，请问，比如类似于扫描件的中文识别这样的场景，本方法如何？

大哥您好，请问最后用的什么方法
