### ISSUE TITLE
Can you release the lmdb transform code?

### ISSUE THREAD

**Issue by luozhengnan** [Canjie-Luo/MORAN_v2#21]
Hi
I want to use Custom data to train the model.Can you release the lmdb transform code to transform the pictures to lmdb files?
Thanks.

**Comment by Canjie-Luo** [comment]
Sure, I had provided a tool link in `README.md`.

**Comment by WJinhai** [comment]
when running the code of create_datsset , occure  MDB_CORRUPTED: Located page was wrong type , what's the happening?

**Comment by Canjie-Luo** [comment]
Can you provide more details for me?

**Comment by luozhengnan** [comment]
> when running the code of create_datsset , occure MDB_CORRUPTED: Located page was wrong type , what's the happening?

Maybe you should run in python2.7.

**Comment by Canjie-Luo** [comment]
Did you use the tool in Python 3? The [tool](https://github.com/bgshih/crnn/blob/master/tool/create_dataset.py) released by [@Baoguang Shi](https://github.com/bgshih) requires Python 2.

**Comment by Canjie-Luo** [comment]
Sorry for that. I will update `README.md` later to remind others.
