### ISSUE TITLE
Error when training custom data

### ISSUE THREAD

**Issue by jisheng047** [Canjie-Luo/MORAN_v2#22]
After generating lmdb dataset, i put it the my path custom data and see the error "my_path is not directory".

Then i put directory path  contains the data.mdb (my generating lmdb) into the script. And i see the error output like this. 

![image](https://user-images.githubusercontent.com/46754815/51513002-2be76700-1e3b-11e9-9cdd-ef76d4cdfdc2.png)

What should i do? Thanks for support

**Comment by Pay20Y** [comment]
Have you fixed it? Thanks!

**Comment by premtibadiya** [comment]
Hey can you tell me what path you gave for tarin_nips, train_csvp and valroot. And also how did you split the lmdb data into train and test.
