### ISSUE TITLE
How to make training process faster?

### ISSUE THREAD

**Issue by jisheng047** [Canjie-Luo/MORAN_v2#23]

**Comment by Canjie-Luo** [comment]
Did you use a Graphic Card?

**Comment by jisheng047** [comment]
@Canjie-Luo  yes, i used GTX-1080 11GB. But not working on multiple gpu, and it use only 2-3 GB on GPU.

**Comment by Canjie-Luo** [comment]
Did you use PyTorch 0.3? How much time for 100 iterations?

**Comment by Canjie-Luo** [comment]
It takes less than 20s for 100 iterations on my 1080Ti.

**Comment by jisheng047** [comment]
@Canjie-Luo it takes about 30-33s for 100 iterations (batch-size=64). I am using PyTorch 1.0.0. 

![image](https://user-images.githubusercontent.com/46754815/51596707-30d81380-1f2c-11e9-86c7-de7874326c3f.png)

**Comment by Canjie-Luo** [comment]
Please downgrade the PyTorch to 0.3.1. Here's the [reason](https://github.com/Canjie-Luo/MORAN_v2/issues/8#issuecomment-455416756).

**Comment by jisheng047** [comment]
@Canjie-Luo  Thanks for your supporting!
