### ISSUE TITLE
Problems downloading file from drive

### ISSUE THREAD

**Issue by DecentMakeover** [Canjie-Luo/MORAN_v2#25]
Hi I'm trying to download the data from Baidu drive from a linux system , but whenever i hit the download button , it always redirects me to install some baidu disk client, which is an exe file.

Is there some way around this? Do you have any plans of uploading it on Gdrive or Dropbox?

Thanks in advance

**Comment by Canjie-Luo** [comment]
Sorry for that. A client on Windows system is necessary to download large datasets. Or you can use the tool (https://github.com/Canjie-Luo/MORAN_v2#data-preparation) to create the datasets on your own computer. The training files are over 20G, which is only supported by Baidu Cloud.

By the way, the access to Google Drive or Dropbox is not very stable for Chinese researchers.

Sorry again.

**Comment by DecentMakeover** [comment]
Okay ,fine

ill see what i can do.Thanks for the quick response

**Comment by Canjie-Luo** [comment]
You're welcome!

**Comment by Canjie-Luo** [comment]
I successfully uploaded the testing sets~ @DecentMakeover

**Comment by Canjie-Luo** [comment]
￼￼/Users/luocanjie/Downloads/1548331676841.jpg

**Comment by Canjie-Luo** [comment]
Here they are~
