### ISSUE TITLE
Testing datasets for training?

### ISSUE THREAD

**Issue by DecentMakeover** [Canjie-Luo/MORAN_v2#28]
Hi 

I am currently downloading the dataset using baidu client disk , the problem is the download speed is very slow, around 100 kbps/sec. my first unrelated question is,if i upgrade to a premium account, will i get a speedup on my download?

Secondly , can  i use the testing datasets for training?

Thanks in advance.

**Comment by Canjie-Luo** [comment]
Actually, I am not sure that your download will be speed up if you upgrade to a premium account outside China. Maybe cropping the images and creating **LMDB** files is a better, and faster choice. And your second question, did you mean to use real data for training? There are many public training datasets, including COCO-Text, ICDAR 2013 and 2015, and IIIT5K.

**Comment by DecentMakeover** [comment]
I was referring to the test data that you posted, can I use them for training?

On 29-Jan-2019, at 9:36 PM, Canjie Luo <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, I am not sure that your download will be speed up if you upgrade to a premium account outside China. Maybe cropping the images and creating LMDB files is a better, and faster choice. And your second question, did you mean to use real data for training? There are many public training datasets, including COCO-Text, ICDAR 2013 and 2015, and IIIT5K.

**Comment by Canjie-Luo** [comment]
Of course. But they are too less for training, I guess. By the way, the testing set should not be one of them.

**Comment by DecentMakeover** [comment]
Ah, what do you mean the testing set should not be one of them ?

On 29-Jan-2019, at 9:50 PM, Canjie Luo <notifications@github.com<mailto:notifications@github.com>> wrote:


Of course. But they are too less for training, I guess. By the way, the testing set should not be one of them.

**Comment by Canjie-Luo** [comment]
But why do you use the testing set for training? I’m confused haha.

**Comment by DecentMakeover** [comment]
Hi
Sorry for the late reply,

The reason is because the download is Taking too long, so I just wanted train this as a starter.

Going to sleep now.

On 29-Jan-2019, at 10:01 PM, Canjie Luo <notifications@github.com<mailto:notifications@github.com>> wrote:


But why do you use the testing set for training? I’m confused haha.

**Comment by Canjie-Luo** [comment]
That’s OK~
