### ISSUE TITLE
About detection

### ISSUE THREAD

**Issue by jisheng047** [Canjie-Luo/MORAN_v2#29]
Hi Canjie-Luo, your project is very awesome!. 

I have trained model and it works well. But now my problem is how can i detect single word in image. I know this question isn't related to your project. Can you give me any solution about detection only word?

I have used EAST for detection word. But EAST also detects long-lines. And for that situation, long-lines not working good on recognition. 

Thanks for your support!

**Comment by Canjie-Luo** [comment]
For the MORAN, the long-line performance is poor due to word-level training datasets, I guess. Fine-tuning EAST on word-level detection datasets may be a quick resolution.
