### ISSUE TITLE
Could you upload demo.pth to an other location?

### ISSUE THREAD

**Issue by Horace89** [Canjie-Luo/MORAN_v2#3]
Hi. It's difficult for non-Chinese users to use Baidu... Could you upload this file to GDrive or somewhere else? Thanks!

**Comment by Canjie-Luo** [comment]
Actually,  for Chinese researchers, it's not easy to access Google Drive or OneDrive, either. But I tried to upload the file last night and updated the `README.md`. It may work. Enjoy yourself~ @Horace89

**Comment by Horace89** [comment]
I was able to download it from Google Drive! Thanks!
