### ISSUE TITLE
about one-stage training

### ISSUE THREAD

**Issue by tanhui2975** [Canjie-Luo/MORAN_v2#33]
Hi @Canjie-Luo,

For cvpr16-80k dataset, we can crop a text region with a tightly bounded box to get regular samples,
and also we can simply crop every text using a minimum circumscribed horizontal rectangle to obtain
irregular samples.

In moran_v1, both regular and irregular samples cropped from cvpr16-80k dataset are used for
curriculum training. So it's the same as one-stage training in moran_v2? Or only irregular one is used?

**Comment by Canjie-Luo** [comment]
Yes, only the irregular one is used in v2. You can use both of them.

**Comment by tanhui2975** [comment]
> Yes, only the irregular one is used in v2. You can use both of them.

Thank you so much!

**Comment by Canjie-Luo** [comment]
You're welcome!
