### ISSUE TITLE
question about your cnn down sampling

### ISSUE THREAD

**Issue by Jiakui** [Canjie-Luo/MORAN_v2#34]
it looks for me that your are down sampling along x-aixs only twice (so the final feature map along x-axis is 1/4 of the image width), but you are down sampling  y-axis five times (so the final feature map along y-axis is 1/32 times of the image height ). 

I wonder, could we down sample along x-axis for more times, for Chinese characters ? Because Chinese characters are usually much bigger than English characters. If we are using the 1/4 down sampling, the training and inference time would be very significant for wide images as the input (we usually get images with 500px width from the detection stage ). 

What is your idea?  Thanks!

**Comment by Canjie-Luo** [comment]
是的，我们在高度方向上用了更多的pooling。您完全可以根据您的需求去改，以适应您的中文任务。据我们所知（也是其他论文的观点，例如edit probability这篇文章），在长序列上attention的效果不好。

**Comment by Jiakui** [comment]
求论文链接

**Comment by Canjie-Luo** [comment]
http://openaccess.thecvf.com/content_cvpr_2018/papers/Bai_Edit_Probability_for_CVPR_2018_paper.pdf

**Comment by Jiakui** [comment]
so , 对于打印体扫描件的长中文识别（一行排版20-30个字），您推荐什么算法呢

**Comment by Jiakui** [comment]
![piece_2](https://user-images.githubusercontent.com/5445793/53160937-eb2e6980-3603-11e9-81f3-a08618d2c546.jpg)

类似这样的图片

**Comment by Canjie-Luo** [comment]
我想这种背景较干净的水平规则文本，用CNN-LSTM-CTC（CRNN）可能更快，也更符合工业需求吧~

**Comment by Jiakui** [comment]
好的~~~ 谢谢了。。。。哪个 CRNN  的 repository 最好呢

**Comment by Canjie-Luo** [comment]
当然是葆光大佬的文章CRNN的实现https://github.com/bgshih/crnn，PyTorch版本在这https://github.com/meijieru/crnn.pytorch
