### ISSUE TITLE
error in python demo.py

### ISSUE THREAD

**Issue by fsluckymao** [Canjie-Luo/MORAN_v2#35]
Hi 
thank you your great paper.
here is my error when i run demo.py.
Could you give me some help plz.

![image](https://user-images.githubusercontent.com/43232995/53141570-8d7e2b00-35cb-11e9-9436-069e71e96a9d.png)

**Comment by Canjie-Luo** [comment]
Please turn off the `CUDA` option to check other dependencies. There may be something wrong with your `CuDNN` environment. I can run the demo with `PyTorch 0.3, CuDNN 7`.

**Comment by fsluckymao** [comment]
thanks for your attention, turn out my Graphics card didnt have enough memory.
