### ISSUE TITLE
如果数据集中含有字母和数字以外的字符该如何处理？

### ISSUE THREAD

**Issue by Evan0-0** [Canjie-Luo/MORAN_v2#37]
类似与ICDAR15中包含了除字母和数字以外的其他类型的字符

**Comment by Canjie-Luo** [comment]
我在`dataset.py`里边把其余的符号都洗掉了，您可以在数据入口那里按照您的要求来清洗。同时，您可以在`--alphabet`（`main.py`或者`.sh`里边）里边定义您的字符列表。

**Comment by Evan0-0** [comment]
OK，明白了，非常感谢您的回答
