### ISSUE TITLE
竖直文本

### ISSUE THREAD

**Issue by chen345** [Canjie-Luo/MORAN_v2#38]
作者你好，请问这个模型可以处理竖直的文本吗？谢谢

**Comment by Canjie-Luo** [comment]
由于这个模型的接口和功能设计是宽大于高的图像，所以暂时没办法直接处理竖直文本。不过，把竖直文本逆时针旋转90度再输入，也许值得尝试。

**Comment by chen345** [comment]
谢谢，还有一个问题，demo.py中的text = torch.LongTensor(1 * 5）这个变量有什么用？
