### ISSUE TITLE
中文识别

### ISSUE THREAD

**Issue by chaoshengzhe** [Canjie-Luo/MORAN_v2#39]
您好，看了上面其它人的提问，似乎MORAN对中文的识别效果不理想，是这样吗？如果是这样的话，您能推荐一下您所知道的中文识别好的算法模型吗？谢谢！

**Comment by Canjie-Luo** [comment]
应该是说在我们的尝试中，基于attention解码的方法对长文本不是很好。请看到这个问题的讨论：https://github.com/Canjie-Luo/MORAN_v2/issues/34

**Comment by chen345** [comment]
谢谢，还有一个问题，demo.py中的text = torch.LongTensor(1 * 5)，length = torch.IntTensor(1)这两个变量有什么用吗？

**Comment by chaoshengzhe** [comment]
哦哦，谢谢，再问您一个问题，我想换一批训练数据，这个数据集大小该如何控制呢，比如说我想识别十个字符，那么我该有多少张训练图片比较合适呢？

**Comment by Canjie-Luo** [comment]
理论上越多越好，数据集包含的背景、字体、形状越多越好。这个需要您先做一部分看看效果。

**Comment by chaoshengzhe** [comment]
哦哦，谢谢！
