### ISSUE TITLE
数据集GT和官网不一致？

### ISSUE THREAD

**Issue by LanluoLing** [Canjie-Luo/MORAN_v2#40]
按照readme下载了你们百度网盘里的数据集。看了看ic15的raw_picture及其GT。和官网的GT不一致啊，怎么回事？不知道其他数据还有没有问题。。。
比如你们IC15的GT如下：
test/word_103.png .UIP
test/word_104.png Tulil
test/word_105.png HALL
test/word_106.png s
test/word_107.png HYE
test/word_108.png Electric
test/word_109.png star
test/word_110.png Air-
而官网公布的GT如下：
word_103.png, "JUR"
word_104.png, "TOWN"
word_105.png, "HALL"
word_106.png, "197"
word_107.png, "AYE"
word_108.png, "Electric"
word_109.png, "star"
word_110.png, "Air"

**Comment by Canjie-Luo** [comment]
请注意，我们提供的原图参考链接来自其他作者的论文（FAN，ICCV，2017），有出入的地方请联系原作者。我们论文中的ICDAR2015使用的是官网的全部测试集，共2077张，请以官网的数据集为准。我们仅用了该链接中，ICDAR2015的1811张版本，而且这个是该作者挑选的，为了避免争议，我们的论文没有汇报这个结果，只在GitHub上提供参考。
