### ISSUE TITLE
python demo.py 报错

### ISSUE THREAD

**Issue by gzhcv** [Canjie-Luo/MORAN_v2#48]
环境是按照readme里提示装的。能够正常训练。但是运行 python demo.py时报错，如下：

`gzh@root0-SCW4350-4:~/ocr/MORAN_v2-master$ python demo.py 

loading pretrained model from ./demo.pth
Traceback (most recent call last):
  File "demo.py", line 55, in <module>
    output = MORAN(image, length, text, text, test=True, debug=True)
  File "/home/gzh/SoftWare/tf1.4/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gzh/ocr/MORAN_v2-master/models/moran.py", line 15, in forward
    x_rectified, demo = self.MORN(x, test, debug=debug)
  File "/home/gzh/SoftWare/tf1.4/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gzh/ocr/MORAN_v2-master/models/morn.py", line 105, in forward
    img = to_pil_image(img_small)
  File "/home/gzh/SoftWare/tf1.4/anaconda2/lib/python2.7/site-packages/torchvision/transforms/transforms.py", line 126, in __call__
    return F.to_pil_image(pic, self.mode)
  File "/home/gzh/SoftWare/tf1.4/anaconda2/lib/python2.7/site-packages/torchvision/transforms/functional.py", line 138, in to_pil_image
    'not {}'.format(type(npimg)))
TypeError: Input pic must be a torch.Tensor or NumPy ndarray, not <class 'torch.FloatTensor'>`

您看看是什么原因呢？

**Comment by DecentMakeover** [comment]
line 11 takes in a image path, 
if you just change that to any other image path, it should work.

can you try and check.

**Comment by gzhcv** [comment]
Thanks for your reply.  The image path is correct.  I've tried before.

**Comment by DecentMakeover** [comment]
okay

can you post some code, its difficult for me to take a guess without looking at some code.

**Comment by gzhcv** [comment]
```
model_path = '/home/gzh/ocr/MORAN_v2-master/demo.pth'

img_path = '/home/gzh/ocr/MORAN_v2-master/demo/0.png'
```
Only line 11 and 10 are changed. I guess something wrong about environment, but it can training correctly.

**Comment by DecentMakeover** [comment]
converter = utils.strLabelConverterForAttention(alphabet, ':')
transformer = dataset.resizeNormalize((100, 32))
image = Image.open(img_path).convert('L')
image = transformer(image)

    if cuda_flag:
        image = image.cuda()
    image = image.view(1, *image.size())
    image = Variable(image)
    text = torch.LongTensor(1 * 5)
    length = torch.IntTensor(1)
    text = Variable(text)
    length = Variable(length)

does your script have the same variables?

**Comment by gzhcv** [comment]
yes

**Comment by DecentMakeover** [comment]
Oh okay, im out of suggestions, somewhere in your code there is float conversion,which is causing this i belive. but im not able to figure where exactly--

**Comment by gzhcv** [comment]
Thanks a lot~ 
I'll check if there is a float conversion.

**Comment by Canjie-Luo** [comment]
@DecentMakeover Thanks a lot for your help. @gzhcv Please make sure that you use the correct version of PyTorch. If the error occurs again, maybe checking the input image in `demo.py` is a better way to debug. Print something or visualize something~

**Comment by gzhcv** [comment]
I can't figure it out. Version of Torch is 0.3.1, the image path is correct. Info as follows

```
gzh@root0-SCW4350-4:~/ocr/MORAN_v2-master$ python
Python 2.7.13 |Anaconda 4.4.0 (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import torch
>>> torch.__version__
'0.3.1'
```
 Running the code in line 39 : `image = Image.open(img_path).convert('L') `
the info of  variable `image` are:
![tim 20190305132832](https://user-images.githubusercontent.com/19361578/53783732-c3b59600-3f4d-11e9-8efa-2d7c92ac0330.png)

 Running the code in line 40: `image = transformer(image)`
the info of  variable `image` are:
![image](https://user-images.githubusercontent.com/19361578/53783912-8271b600-3f4e-11e9-8725-ee4fc22167b0.png)

**Comment by DecentMakeover** [comment]
Im curious,what tool are you using to visualize this?

**Comment by gzhcv** [comment]
Pychram

**Comment by gzhcv** [comment]
Pycharm

**Comment by DecentMakeover** [comment]
Okay

**Comment by DecentMakeover** [comment]
make a snippet of your demo.py and post it here, ill run it on my system and see if it works

**Comment by gzhcv** [comment]
```
converter = utils.strLabelConverterForAttention(alphabet, ':')
transformer = dataset.resizeNormalize((100, 32))
image = Image.open(img_path).convert('L')
image = transformer(image)

if cuda_flag:
    image = image.cuda()
image = image.view(1, *image.size())
image = Variable(image)
text = torch.LongTensor(1 * 5)
length = torch.IntTensor(1)
text = Variable(text)
length = Variable(length)

max_iter = 20
t, l = converter.encode('0'*max_iter)
utils.loadData(text, t)
utils.loadData(length, l)
output = MORAN(image, length, text, text, test=True, debug=True)
```

**Comment by gzhcv** [comment]
I just changed the path of image and model in demo.py,  and no dependency files was modified.  Torch version was checked, image is loaded correctly. So it's really strange.

**Comment by DecentMakeover** [comment]
The code you sent is not enough, post the entire demo.py file or go here https://gist.github.com/ paste your code and share the link here

**Comment by gzhcv** [comment]
https://gist.github.com/gzhcv/f84101dfbad185abc20d32d98e08d2d2

**Comment by DecentMakeover** [comment]
The script runs beautifully on my system without any modifications.
I freezed my enviornment and posted the packages in them, it also contains redundant packages, just for you to cross check

[my_pack.txt](https://github.com/Canjie-Luo/MORAN_v2/files/2929614/my_pack.txt)

**Comment by gzhcv** [comment]
Wow,  thanks so much.  I'll look into your packages.

**Comment by DecentMakeover** [comment]
Amazing! Glad you could make it work!

**Comment by Canjie-Luo** [comment]
Sorry for that. You can pull request then you will become one of contributor~
