### ISSUE TITLE
Making inference faster

### ISSUE THREAD

**Issue by DecentMakeover** [Canjie-Luo/MORAN_v2#49]
Any suggestions on how i may be able to make inference faster?

currently it takes 0.33 seconds for it to produce a single output.

#############-Update
It seems like loading the model is taking most of the time- 
loading the model takes 0.31 seconds

Thanks.

**Comment by Canjie-Luo** [comment]
Load the model once and keep the model in-memory. Call the inference function every time you need.

**Comment by DecentMakeover** [comment]
Okay, ill look into it.Thanks.
