### ISSUE TITLE
offset map has only one channel in MORAN_v2?

### ISSUE THREAD

**Issue by gzhcv** [Canjie-Luo/MORAN_v2#54]
Hi, 如果我没理解错代码的话，V2版本的代码中Offset Map只有一个通道，只回归了高度方向的偏移值做矫正。如是这样，为什么这么做呢？

**Comment by Canjie-Luo** [comment]
您好，在v1中我们发现在水平方向上，x的偏移值不大，所以在v2中去掉x的offset，相当于去掉了一半的预测参数，使得模型收敛更快。您也可以改成两个通道，对于其他的任务应该更加灵活一些。

**Comment by gzhcv** [comment]
多谢解答。从文章中确实也看到这种现象，感觉大多是竖直方向上的拉伸。
