### ISSUE TITLE
Irrelevant predictions

### ISSUE THREAD

**Issue by DecentMakeover** [Canjie-Luo/MORAN_v2#56]
Hi

I am testing Moran on different languages, even though it is trained only on English and special characters.
when i input a test image which has a different language, instead of predicting nothing, the model predicts random characters.

Can something be done to discourage this behaviour?

Thanks in advance.

**Comment by gzhcv** [comment]
The test image has multi-language (including English) ?  And the English character is also misclassified?

**Comment by DecentMakeover** [comment]
No the test image only has words of different language, but instead of predicting nothing, Moran predicts random english charcters, even though there is no english word present.

Any ideas?

**Comment by gzhcv** [comment]
I think it should be random english charcters. As mentioned in paper, 

> The ASRN outputs 37 classes,including 26 letters, 10 digits and a symbol standing for \EOS".

So the output sequence {\EOS} is expected in your situation. But no training sample is labeled {\EOS}. Maybe adding some image with different language and labeled {\EOS} will work?

**Comment by DecentMakeover** [comment]
okay, let me see what i can do.

Thanks for the response.
