### ISSUE TITLE
Dataset problem~

### ISSUE THREAD

**Issue by JingLiJJ** [Canjie-Luo/MORAN_v2#59]
Hi, 

I'm a little confused about dataset. You use cpvr2016 and nips2014 to train the model, right? During training, you also use validation dataset? Which validation dataset did you use? 

Btw, where can I test the model and get an accuracy? test.py file?

**Comment by gzhcv** [comment]
You could look into `Data Preparation` part in `README`.  Most of the public dataset is provided, you could setting the validation dataset in `train_MORAN.sh`.

**Comment by Canjie-Luo** [comment]
@gzhcv Thanks a lot!

**Comment by JingLiJJ** [comment]
> You could look into `Data Preparation` part in `README`. Most of the public dataset is provided, you could setting the validation dataset in `train_MORAN.sh`.

How about test part? Where can I test the model and get an accuracy directly?

**Comment by gzhcv** [comment]
@JingLiJJ  I just running `train_MORAN.sh` to get the accuracy, it's not a good method. Maybe there is another way to get the accuracy (e.g. look into the `val()` function in `main.py`). And, it seems no exsit code to get the accuracy directly

**Comment by Canjie-Luo** [comment]
@JingLiJJ @gzhcv It is an on-the-fly way for evaluation, following CRNN and ASTER.

**Comment by JingLiJJ** [comment]
> @JingLiJJ I just running `train_MORAN.sh` to get the accuracy, it's not a good method. Maybe there is another way to get the accuracy (e.g. look into the `val()` function in `main.py`). And, it seems no exsit code to get the accuracy directly

Thanks~ I got it.
