### ISSUE TITLE
测试准确率达不到Val的水准？

### ISSUE THREAD

**Issue by fsluckymao** [Canjie-Luo/MORAN_v2#60]
Hi: @Canjie-Luo 
我在训练过程中跑的val准确率有95.05%,并且我保存了这个模型。再用这个模型跑测试，达不到95.05%的准确率，测试与val的区别只有数据是以图片的格式一张一张(不是lmdb)读的，来一张测一张的样子，最后的准确率没有val时候的高，您能帮助我吗？

**Comment by fsluckymao** [comment]
Hi: @Canjie-Luo:
另外一个问题，我把val的代码抽出来，单独做val，把batchsize改成32，16，8，4准确率都不变(95.05)，没问题，但是改成1的话准确率就直接变成4.1%...... 您对此有什么看法吗？:confused:

**Comment by Canjie-Luo** [comment]
我猜想，当batchsize为1时，gt为一个字符串，然后gt[0]只是字符串中的一个字符，自然就错了。应该是这样的，您简单输出一些变量就可以发现。这是一个bug，回头我看看。

**Comment by Canjie-Luo** [comment]
这个batch的gt为一个字符串，而不是一个list之类的

**Comment by fsluckymao** [comment]
好，我去试试，其实第一个问题是我还不知道怎么解决的，期待您的帮助...
thanks!

**Comment by Canjie-Luo** [comment]
客气～

**Comment by Canjie-Luo** [comment]
第一个问题，可能需要把原来对的，后边错了的，分析一下。可能是数据入口的处理不一致。

**Comment by fsluckymao** [comment]
OK,我在分析.
我看您的FP算法里面感觉和论文里的不大一样..
这里的注释好像写反了，导致你的FP算法作用到batchsize的维度上去了..
https://github.com/Canjie-Luo/MORAN_v2/blob/08713b0dd56258fd546034c10393ee15fe469567/models/asrn_res.py#L49
alpha的shape不应该是 nT * nB吗？

**Comment by Canjie-Luo** [comment]
这里的注释是反的，我后边统一更新一下。FP好像没有错？

**Comment by Canjie-Luo** [comment]
这里确实写反了，FP的话，我明天来看看，好像是有点问题。但是居然还能收敛？

**Comment by Canjie-Luo** [comment]
FP的bug已经修改。 @fsluckymao 谢谢！

**Comment by fsluckymao** [comment]
不客气，共同进步.

**Comment by vc384** [comment]
可能是BN的问题
