### ISSUE TITLE
训练中的字符集问题

### ISSUE THREAD

**Issue by bjlgcxc** [Canjie-Luo/MORAN_v2#62]
你好，我想请问下，论文模型的训练数据集如果是synth90k的话，这个数据只包含字母/数字，不包含标点符号。那么在进行测试时，比如ICDAR15这种带标点符号的数据集，你们是如何测试的呢？
是忽略标点符号来计算准确率，还是说就按照正常的来计算呢，因为这样训练的模型没有标点符号的类，肯定预测不出标点符号。

**Comment by bjlgcxc** [comment]
另外还有一个问题，MORN能否单独训练呢？

**Comment by Canjie-Luo** [comment]
您好！
1、依照最近的论文的实验设置，在所有的测试数据集中，我们过滤了符号，只保留了数字和字母；
2、MORN是通过弱监督来训练的，不需要额外的标注信息，这也是一个创新点之一。不知道您说的单独训练是什么意思呢？

**Comment by bjlgcxc** [comment]
感谢回答，这里说的单独训练指的是不接后面的attention网络，可能是我想得太简单了，您这里说的弱监督指的是后面的attention网络的反传到MORN的梯度来进行弱监督吗？

**Comment by Canjie-Luo** [comment]
客气了~是的，MORN的训练是通过后边的识别网络的梯度来指导的。如果单独训练的话，需要label来指导，做这么多的label，很困难吧？

**Comment by bjlgcxc** [comment]
嗯，是的，明白啦

**Comment by bjlgcxc** [comment]
再请教您一个问题哈，我准备用morn来做矫正的，当训练完模型后，应该如何用模型来做矫正呢？我想做的是输入原图，然后输出矫正后的图片。 因为模型输入的是transform之后的图像，输出的图片应该也是对应transform过的，这个怎么整.

**Comment by Canjie-Luo** [comment]
@bjlgcxc 我给出的`demo.py`里边就有返回transform之后的图像，您可以依照里边的代码去改，怎么显示，包括输出的大小，都是可以调整的。

**Comment by bjlgcxc** [comment]
你好，请问你用ctc训过吗，对比attention方法而言，效果如何呢？

**Comment by Canjie-Luo** [comment]
请问您说的还是这个任务吗？这个您可以参考CRNN的文章。

**Comment by bjlgcxc** [comment]
嗯，是的，主要是想看看ctc和attention的精度差多少

**Comment by Canjie-Luo** [comment]
在这个任务上，我猜CTC稍逊一筹，也欢迎您分享您的实验～
