### ISSUE TITLE
关于使用词典进行预测

### ISSUE THREAD

**Issue by YeeeQiAn** [Canjie-Luo/MORAN_v2#63]
你好，我想请问一下，如何使用词典进行最后的结果预测。我看你的实验结果里是有这一部分的，但是代码里似乎没有给出，能方便将相关代码给出来吗？再次感谢

**Comment by Canjie-Luo** [comment]
抱歉没能及时回复。当时我是根据输出的概率矩阵，直接选择置信度最高的单词作为最后结果。后边组内的其他同学建议我根据预测的单词和候选的单词的编辑距离来选，似乎效果更好点。由于时间太久了，暂时找不到当时的代码，抱歉，也建议您使用后一种方式去选择单词。

**Comment by YeeeQiAn** [comment]
谢谢，还有一个问题，就是icdar03词典是怎么生成的？

**Comment by Canjie-Luo** [comment]
好的，您可以发邮件给我，我再根据你的邮箱发过去。

**Comment by YeeeQiAn** [comment]
已经给你发邮件了，十分感谢
