### ISSUE TITLE
About testing

### ISSUE THREAD

**Issue by Kryptonites** [Canjie-Luo/MORAN_v2#64]
1. What does the test.py for?
2. What's the deference between val() in main.py and demo.py while processing the output of MORAN?

**Comment by Canjie-Luo** [comment]
1. For the testing of your environment;
2. They are totally the same.

**Comment by Kryptonites** [comment]
When decoding the results, you use tensor.numel() to filter only one character among the results, I wonder why you dump the other results?

**Comment by Canjie-Luo** [comment]
I am confused about your question. Actually, a predicted result contains several characters.

**Comment by Kryptonites** [comment]
In demo.py, argument 'sim_preds' contains only one character, what does it for?

**Comment by Canjie-Luo** [comment]
Did you use my demo pic?

**Comment by Kryptonites** [comment]
I re-train a new model with synthetic dataset. But when testing, there was terribly result, so I was trying to figure out why.
