### ISSUE TITLE
如何制作训练数据集？

### ISSUE THREAD

**Issue by chaoshengzhe** [Canjie-Luo/MORAN_v2#65]
我看了项目里给的lmdb格式数据，我不知道这个格式数据生成的原始图片的格式是怎样的，我想用生成自己数据集，该如何做呢？

**Comment by chaoshengzhe** [comment]
是一张图片对应一个txt文件，txt文件里写上图片里的字符吗？

**Comment by Canjie-Luo** [comment]
您好，请参照`README.md`里边的工具制作LMDB，您可以根据您自己的需要来修改工具的接口。
