### ISSUE TITLE
Dimension in the model and dimension in the checkpoint are incompatible.

### ISSUE THREAD

**Issue by pp3993** [Canjie-Luo/MORAN_v2#66]
Hi,
I trained the model on my own data, where change in alphabet shown here.

alphabet='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/.>,()-')
I used create_dataset.py file to create mdb file.

```
File "demo.py", line 31, in <module>
    MORAN.load_state_dict(MORAN_state_dict_rename)
  File "/home/payal/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 519, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named ASRN.attentionL2R.char_embeddings, whose dimensions in the model are torch.Size([38, 256]) and whose dimensions in the checkpoint are torch.Size([71, 256]).
```
Can you help, please? Couldn't understand what is the issue?

**Comment by Canjie-Luo** [comment]
Because the parameter in my `demo.pth` is used for 38 classes. You can skip the unmatched parameters and load other parameters. Please ref to the PyTorch offical docs.
