### ISSUE TITLE
MORN question~

### ISSUE THREAD

**Issue by JingLiJJ** [Canjie-Luo/MORAN_v2#69]
您好。我想问一下，在MORN里
图片过了CNN出来的size为什么是1*3*11，而不是paper上写的2*3*11呢？
还有，
https://github.com/Canjie-Luo/MORAN_v2/blob/1eb698848025900aa4638c5ca6e2605cb4681f58/models/morn.py#L66-L69
为什么只对y轴进行了矫正呢？还是我理解错了？

**Comment by Canjie-Luo** [comment]
您好，MORAN v1用的是两个维度的，即xy，但是我们发现cropped text基本没有水平位移的问题，所以MORAN v2去掉了x维度，只在竖直方向上纠正字符，能应用于大多数场景，同时也更好端到端训练，毕竟解空间变小了。

**Comment by JingLiJJ** [comment]
感谢回答！那我想问一下这个模型可以做不定长训练么？

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Canjie-Luo** [comment]
您说的不定长指的是？

**Comment by JingLiJJ** [comment]
在训练的时候固定图片的高度，然后等比例缩放长度。像CRNN一样

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Canjie Luo <notifications@github.com>
发送时间: Monday, May 6, 2019 2:39:17 PM
收件人: Canjie-Luo/MORAN_v2
抄送: JingLiJJ; Author
主题: Re: [Canjie-Luo/MORAN_v2] MORN question~ (#69)


您说的不定长指的是？

―

**Comment by Canjie-Luo** [comment]
这个是可以实现的，您可以按照CRNN写一个alignCollate（dataset.py中），或者在MORN中随机缩放target_W。

**Comment by JingLiJJ** [comment]
好哒。谢谢！

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tanhui2975** [comment]
请问第80行的代码应该是x_rectified = nn.functional.grid_sample(x, offsets_x)
还是x_rectified = nn.functional.grid_sample(x_rectified, offsets_x) ？ @Canjie-Luo 
https://github.com/Canjie-Luo/MORAN_v2/blob/1eb698848025900aa4638c5ca6e2605cb4681f58/models/morn.py#L66-L80

**Comment by Canjie-Luo** [comment]
您好，原代码是对的，在纠正后的图像上预测offset，但是在原图x上采样。

tanhui2975 <notifications@github.com> 于2019年7月18日周四 下午5:17写道：
