### ISSUE TITLE
您好,有些模型有最大字符长度,该模型没有这个参数,用任意长度中文图片都可以训练吗?该模型的预测机制是不需要最大label长度这个参数么?

### ISSUE THREAD

**Issue by tnkong** [Canjie-Luo/MORAN_v2#70]

**Comment by Canjie-Luo** [comment]
所有的模型都没有长度限制，只是在训练的时候考虑显存和时间的开销，限制了最大长度。在实际情况中，短文本也占多数，除非是扫描的文档，可能会特别长。

**Comment by tnkong** [comment]
其实就是ｄｅｃｏｄｅｒ在解码过程中产生的ｓｅｑ的长度其实是可以不做任何限制的，无限长的ｓｅｑ都可以产生，我之前用的是ｔｅｎｓｏｒｆｏｗ的BａｓｉｃDecoder这个，有一个最大迭代次数max_iter的变量，限制了ｄｅｃｏｄｅｒ生成的ｓｅｑ的最大长度，我需要修改代码解除这种限制

**Comment by Canjie-Luo** [comment]
是的，这里没有限制长度。
