### ISSUE TITLE
Fractional pickup index

### ISSUE THREAD

**Issue by marcbelmont** [Canjie-Luo/MORAN_v2#75]
https://github.com/Canjie-Luo/MORAN_v2/blob/be56705c1e0c2fa960f443d77049903f37ce8251/models/fracPickup.py#L24

Shouldn't it be:
`if idx <= 0 or idx >= x_shape[3]:`

**Comment by marcbelmont** [comment]
Have you tried picking `idx` using the maximum of `x` instead of randomly?

Is fractional pickup also used at inference time? Wouldn't the random nature of the function be a problem?

**Comment by Canjie-Luo** [comment]
Emm, you are right. It's a bug. But I guess the "EOS" is near the x_shape[3] and your change may not bring improvement. 
Actually, the fractional pickup is only used in the training. Thanks.
