### ISSUE TITLE
端到端的训练并没有出现矫正的情况？是怎么回事？

### ISSUE THREAD

**Issue by lzmisscc** [Canjie-Luo/MORAN_v2#77]

**Comment by Canjie-Luo** [comment]
您好，请问可以详细描述一下您的情况吗？

**Comment by lzmisscc** [comment]
作者，你好，我使用你的代码进行训练，刚开始的时候较大幅度的矫正，但是到后期矫正的效果就慢慢消失了，另外，在训练中还出现了，本来在验证集中60%的准确率就突然变为0之后就再也没能够收敛了

**Comment by Canjie-Luo** [comment]
您好，大致了解了您的情况，这也是半年来第一次不稳定训练的报告。请问您完全按照我的实验环境和设置进行了实验吗，后期有降低学习率之类的吗？

**Comment by lzmisscc** [comment]
这是在还没有降低学习率之前的情况，我使用的是python3.6和pytorch4.1版本

**Comment by Canjie-Luo** [comment]
我们尝试了PyTorch 0.3.1 版本，没有问题，理论上PyTorch 0.4版本也只是速度问题。您试试0.3版本？

**Comment by wuxiaolianggit** [comment]
File "main.py", line 243, in <module>
    acc_tmp = val(test_dataset, criterion)
  File "main.py", line 186, in val
    preds = MORAN(image, length, text, text_rev, test=True)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/wuxl/ocr/MORAN_v2/models/moran.py", line 20, in forward
    preds = self.ASRN(x_rectified, length, text, text_rev, test)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/wuxl/ocr/MORAN_v2/models/asrn_res.py", line 256, in forward
    output = self.attention(rnn, length, text, test)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/wuxl/ocr/MORAN_v2/models/asrn_res.py", line 129, in forward
    probs = Variable(torch.zeros(nB*num_steps, self.num_classes))
TypeError: an integer is required

@lzmisscc 请问大神有遇到过这个情况吗

**Comment by lzmisscc** [comment]
> File "main.py", line 243, in 
> acc_tmp = val(test_dataset, criterion)
> File "main.py", line 186, in val
> preds = MORAN(image, length, text, text_rev, test=True)
> File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in **call**
> result = self.forward(*input, **kwargs)
> File "/data/wuxl/ocr/MORAN_v2/models/moran.py", line 20, in forward
> preds = self.ASRN(x_rectified, length, text, text_rev, test)
> File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in **call**
> result = self.forward(*input, **kwargs)
> File "/data/wuxl/ocr/MORAN_v2/models/asrn_res.py", line 256, in forward
> output = self.attention(rnn, length, text, test)
> File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in **call**
> result = self.forward(_input, **kwargs) File "/data/wuxl/ocr/MORAN_v2/models/asrn_res.py", line 129, in forward probs = Variable(torch.zeros(nB_num_steps, self.num_classes))
> TypeError: an integer is required
> 
> @lzmisscc 请问大神有遇到过这个情况吗

把torch的版本降一下
