### ISSUE TITLE
how to use mdb file to trian?

### ISSUE THREAD

**Issue by mathpopo** [Canjie-Luo/MORAN_v2#79]
--train_nips path_to_dataset 
--train_cvpr path_to_dataset 
--valroot path_to_dataset 
when i entry the baidupan:i found all are lock.mdb data.mdb,sorry i don not know how to use them,plz tell some?

**Comment by bendiazntc** [comment]
Yes

**Comment by Canjie-Luo** [comment]
Hi~ Please use the folder root (containing `data.mdb` and `lock.mdb`) of the dataset as `path_to_dataset`.

**Comment by johnSmith1990** [comment]
> Hi~ Please use the folder root (containing `data.mdb` and `lock.mdb`) of the dataset as `path_to_dataset`.

thanks. what is for validation dataset? you mentioned here the datasets `svt_p_645`, `svt_647`, `IIIT5K_3000`,`ic15_2077` and some other datasets for validation. Do we have to combine these datasets and produce one `lmdb` file for all of them or choose one of these datasets for validation?
thanks

**Comment by Canjie-Luo** [comment]
Either way, as you like~
