### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by Jwicaksana** [Canjie-Luo/MORAN_v2#80]
Hi @Canjie-Luo, this is not an issue per say but I am wondering if it is possible to download the pre-trained model?

Also for the Baidu download, is it possible to download without having mainland mobile number?

Thanks!

**Comment by Canjie-Luo** [comment]
Hi~ Thanks for your attention.

I have uploaded the pre-trained model to Google Drive (Please refer to
`README.md`). Maybe it is more convenient for you.



Jwicaksana <notifications@github.com> 于2019年7月9日周二 下午8:14写道：

**Comment by Jwicaksana** [comment]
Thanks! @Canjie-Luo
