### ISSUE TITLE
lmdb中data.mdb 大小不一致问题

### ISSUE THREAD

**Issue by jiaying96** [Canjie-Luo/MORAN_v2#85]
自己用create_dataset.py生成cute80 data.mdb文件大小为8.75MB 而作者给出的是17.52MB，其他数据集也大概是二倍关系？
@Canjie-Luo 请问您是怎么生成的？def createDataset(outputPath, imagePathList, labelList, lexiconList=None, checkValid=True) 函数中lexiconList您传参数了吗

**Comment by Canjie-Luo** [comment]
您好，我的数据集中只有图像和对应的标签，没有其他数据。验证两个数据集之间的差异，最直观的做法就是用训练好的模型测试一下，看看精度的差异，然后好找问题～

**Comment by jiaying96** [comment]
因为我想区分大小写字母，而用您给的data.mdb测试集在程序里打印输出label已经是小写了， 所以我想用原始图像和标签重新生成data.mdb试一下，发现与您给的文件大小不同，请问您将是什么时候，怎样将测试集的label转为小写字母的？

**Comment by Canjie-Luo** [comment]
抱歉，遗漏了回复，这个我也忘记了，可能是组内同学整理过的数据。要麻烦您再生成一次～
