### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by YacobBY** [Canjie-Luo/MORAN_v2#87]
Hello,

In the  bottom section of your Readme.txt you state that the repo is only free for academic use, however the license file you included (MIT License) it specifically states that it is free for commercial use as well. You might want to update the license file to something more restricted.

**Comment by Canjie-Luo** [comment]
Thanks for your kind reminder~

**Comment by Canjie-Luo** [comment]
As I borrowed some codes from other open repos, it is better to remain the MIT License. Maybe I can update the License in the next new version of MORAN. Thanks again.
