### ISSUE TITLE
Difficult to recognition 'L' and 'AA' in a well aligned random sequence.

### ISSUE THREAD

**Issue by huntkao** [Canjie-Luo/MORAN_v2#99]
I find Moran V2 usually recognize 'L' as '1' and 'AA' as '4A' in a horizontally well-aligned random character sequence. Since the input image (approximately 200x64) has nice contrast and the sequence length is around 7~10 characters, I think the image quality is sufficient, even in 100x32 scale level. The results thus really confuse me.
Note: I use the pre-trained model. Demo code is not changed. 
Is there any way to improve/fix this or did I miss something important about Moran usage?

Any help is appreciated.

**Comment by Canjie-Luo** [comment]
Thanks for your attention. The best way is to fine-tune MORAN on your training dataset, I guess.
